"""Initial Migration - implement enum for choices

Revision ID: 10b6e6b24d5f
Revises: 
Create Date: 2026-02-26 03:51:15.095241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b6e6b24d5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.alter_column('intermediate_outcome',
               existing_type=sa.TEXT(),
               type_=sa.Enum('EQUITY', 'QUALITY', 'UTILIZATION', 'FINANCIAL_RISK', name='intermediate_outcome_enum'),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Enum('FIXED_ASSETS', 'INFRASTRUCTURE', 'RENOVATION_REPAIRS', 'PROGRAMS', 'OTHERS', name='budget_category_enum'),
               existing_nullable=True)
        batch_op.alter_column('health_care_service',
               existing_type=sa.TEXT(),
               type_=sa.Enum('PRIMARY', 'SECONDARY', 'TERTIARY', name='health_care_service_enum'),
               existing_nullable=True)
        batch_op.alter_column('primary_health_care',
               existing_type=sa.TEXT(),
               type_=sa.Enum('BASIC_HEALTHCARE_PROVISION_FUND', 'ROUTINE_IMMUNIZATION', 'MATERNAL_NEWBORN_CHILD_HEALTH', 'NUTRITION', 'MALARIA', 'FAMILY_PLANNING', name='primary_health_service_enum'),
               existing_nullable=True)
        batch_op.alter_column('secondary_health_care',
               existing_type=sa.TEXT(),
               type_=sa.Enum('BASIC_HEALTHCARE_PROVISION_FUND', 'ROUTINE_IMMUNIZATION', 'MATERNAL_NEWBORN_CHILD_HEALTH', 'NUTRITION', 'MALARIA', 'FAMILY_PLANNING', name='secondary_health_service_enum'),
               existing_nullable=True)
        batch_op.alter_column('tertiary_health_care',
               existing_type=sa.TEXT(),
               type_=sa.Enum('SPECIALISED_CLINICAL_SERVICES', 'ADVANCED_DIAGNOSTIC_INFRASTRUCTURE', 'MANAGEMENT_RARE_COMPLEX', 'MEDICAL_EDUCATION_RESEARCH', 'SPECIALISED_SURGICAL', 'GENERAL_SPECIALIST_CLINICAL', 'LABORATORY_PATHOLOGY', 'HOSPITAL_INFRASTRUCTURE', 'ICT_DIGITAL_HEALTH', 'ICU_NICU', 'EMERGENCY_TRAUMA', name='tertiary_health_service_enum'),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_survey_responses_health_care_service'), ['health_care_service'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_responses_intermediate_outcome'), ['intermediate_outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_responses_primary_health_care'), ['primary_health_care'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_responses_secondary_health_care'), ['secondary_health_care'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_responses_tertiary_health_care'), ['tertiary_health_care'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_responses_tertiary_health_care'))
        batch_op.drop_index(batch_op.f('ix_survey_responses_secondary_health_care'))
        batch_op.drop_index(batch_op.f('ix_survey_responses_primary_health_care'))
        batch_op.drop_index(batch_op.f('ix_survey_responses_intermediate_outcome'))
        batch_op.drop_index(batch_op.f('ix_survey_responses_health_care_service'))
        batch_op.alter_column('tertiary_health_care',
               existing_type=sa.Enum('SPECIALISED_CLINICAL_SERVICES', 'ADVANCED_DIAGNOSTIC_INFRASTRUCTURE', 'MANAGEMENT_RARE_COMPLEX', 'MEDICAL_EDUCATION_RESEARCH', 'SPECIALISED_SURGICAL', 'GENERAL_SPECIALIST_CLINICAL', 'LABORATORY_PATHOLOGY', 'HOSPITAL_INFRASTRUCTURE', 'ICT_DIGITAL_HEALTH', 'ICU_NICU', 'EMERGENCY_TRAUMA', name='tertiary_health_service_enum'),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('secondary_health_care',
               existing_type=sa.Enum('BASIC_HEALTHCARE_PROVISION_FUND', 'ROUTINE_IMMUNIZATION', 'MATERNAL_NEWBORN_CHILD_HEALTH', 'NUTRITION', 'MALARIA', 'FAMILY_PLANNING', name='secondary_health_service_enum'),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('primary_health_care',
               existing_type=sa.Enum('BASIC_HEALTHCARE_PROVISION_FUND', 'ROUTINE_IMMUNIZATION', 'MATERNAL_NEWBORN_CHILD_HEALTH', 'NUTRITION', 'MALARIA', 'FAMILY_PLANNING', name='primary_health_service_enum'),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('health_care_service',
               existing_type=sa.Enum('PRIMARY', 'SECONDARY', 'TERTIARY', name='health_care_service_enum'),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.Enum('FIXED_ASSETS', 'INFRASTRUCTURE', 'RENOVATION_REPAIRS', 'PROGRAMS', 'OTHERS', name='budget_category_enum'),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('intermediate_outcome',
               existing_type=sa.Enum('EQUITY', 'QUALITY', 'UTILIZATION', 'FINANCIAL_RISK', name='intermediate_outcome_enum'),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
